name: Agents Kit update

on:
  pull_request:
    paths:
      - package.json
      - yarn.lock

jobs:
  agents-kit-skills-install:
    permissions:
      contents: write
      id-token: write
      packages: read
      pull-requests: read
    uses: contentful/developer-platform/.github/workflows/job-agents-kit-update.yaml@4446d81c9645df1a7f106acfb1645540302435d3
    secrets: inherit
