name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  cancel_previous:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # 0.9.1
      with:
        workflow_id: ${{ github.event.workflow.id }}
  build-and-test:
    name: "Test (Node.js v${{ matrix.node-version }})"
    needs: cancel_previous
    runs-on: 'ubuntu-latest'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        node-version: [ 18, 20, 21 ]
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install
        run: yarn install --frozen-lockfile --ignore-engines
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --coverage
